/**
 * Typed access to the official FBR template lists.
 * The JSON is generated by scripts/extract-iris-sales-references.cjs.
 */

import data from "./reference-data.json";

export interface TemplateReference {
  templateFile: string;
  templateKind: "DSI" | "DPI";
  templateVersion: string;
  headerRows: string[][];
  documentTypes: string[];
  partyTypes: string[];
  saleTypes: string[];
  reasons: string[];
  unitsOfMeasure: string[];
  provinces: string[];
  rates: Array<number | string>;
  sroNumbers: string[];
  itemSerials: string[];
}

export const SALES_TEMPLATE: TemplateReference =
  data.sales as unknown as TemplateReference;
export const PURCHASE_TEMPLATE: TemplateReference =
  data.purchase as unknown as TemplateReference;

/** Template versions the engine has been checked against. */
export const SUPPORTED_SALES_TEMPLATE_VERSIONS = [SALES_TEMPLATE.templateVersion];
export const SUPPORTED_PURCHASE_TEMPLATE_VERSIONS = [
  PURCHASE_TEMPLATE.templateVersion,
];
